language: python

python:
  - "3.6"

env:
  - ADMIN_PARTY=true
  - ADMIN_PARTY=false

services:
  - couchdb

install: "pip install -r requirements.txt && pip install -r test-requirements.txt"
# command to run tests
script:
    - pylint ./src/cloudant
    - nosetests -w ./tests/unit

notifications:
  email: false
